WIP Extend FPC Shim support
hyperledger/fabric-private-chaincode pull request #637
Opened 2021-11-08 17:44 UTC by mbrandenburger

- add get_signed_proposal
- add get_tx_id
- add get_channel_id
- add get_transient_data

Signed-off-by: Marcus Brandenburger <bur@zurich.ibm.com>

2021-11-09 14:18 UTC, mbrandenburger commented
TBD what to do with the transient data?

2021-11-10 08:23 UTC, mbrandenburger commented
> TBD what to do with the transient data?

transient data support will be separate PR.

2021-11-15 21:30 UTC, bvavala requested changes
Two parts: 1) shim extensions and 2) shim internals.

1. Overall, the shim extensions look good. Those can provide the chaincode with useful information which was either previously attested, or extracted from the signed proposal.

Missing: comments and documentation regarding the channel id and, particularly, the creator. The creator is not (and cannot be) validated against the ledger/MSP -- the enclave does not have trustworthy data to do so.

2. The shim internals need some more work. 
First, some data is extracted from the signed proposal, but the signed-proposal signature is not checked. Although documented, this could open to unintended consequences.

Second, the channel id and creator are extracted from the proposal, but the former is already passed to (and attested by) the enclave at init time, while the latter already has a shim API for the name. In both cases, consistency is not checked. Again, this could open to unintended consequences.

2021-11-29 17:25 UTC, mbrandenburger commented on ecc_enclave/enclave/enclave.cpp
> +        ctx.creator = ByteArray(signature_header.creator->bytes,
right - I figured out how to extract creator_name directly from the signed proposal, so I jusggest just to remove the ocall. WIP

2021-11-29 17:25 UTC, mbrandenburger commented on ecc_enclave/enclave/enclave.cpp
> +        ctx.channel_id = std::string(channel_header.channel_id);
right! added

2021-12-01 14:20 UTC, mbrandenburger commented
I just experienced that this code is not compatible with Idemix.

With current FPC, Idemix is working as long as you not call `get_creator_name`. The problem with Idemix is that the serialized identity does not contain a x509 cert (in pem format), instead it contains a serialized idemix identity (as protobuf msg). As said, this is only a problem with `get_creator_name`, where we try to extract the cert subject.

That is, the code in this PR fails when it tries to parse the x509 as it is actually an idemix identity.

2021-12-01 14:52 UTC, mbrandenburger commented
> I just experienced that this code is not compatible with Idemix.
> 
> With current FPC, Idemix is working as long as you not call `get_creator_name`. The problem with Idemix is that the serialized identity does not contain a x509 cert (in pem format), instead it contains a serialized idemix identity (as protobuf msg). As said, this is only a problem with `get_creator_name`, where we try to extract the cert subject.
> 
> That is, the code in this PR fails when it tries to parse the x509 as it is actually an idemix identity.

2021-12-06 09:22 UTC, mbrandenburger commented
@bvavala are you still looking at this?

2021-12-07 16:12 UTC, bvavala commented
comments addressed - not tested in hw mode

2021-12-07 16:12 UTC, merged